# Provider configuration is generated by Terragrunt (infra/live/root.hcl).
# Do not run terraform in this directory; apply from infra/live/accounts.
terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.40.0"
    }
    local = {
      source  = "hashicorp/local"
      version = ">= 2.4.0"
    }
  }
}
